# Generated by Django 5.0.6 on 2026-02-02 18:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('WEB', 'Web'), ('MCP', 'MCP')], max_length=10)),
                ('tool_name', models.CharField(max_length=120)),
                ('input_summary', models.TextField()),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAIL', 'Fail')], max_length=10)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DSAProblem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('platform', models.CharField(choices=[('LEETCODE', 'LeetCode'), ('GFG', 'GFG'), ('CUSTOM', 'Custom')], default='LEETCODE', max_length=20)),
                ('link', models.URLField(blank=True)),
                ('difficulty', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('statement', models.TextField(blank=True)),
                ('solution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_type', models.CharField(choices=[('DSA_PROBLEM', 'DSA Problem'), ('DESIGN_TOPIC', 'Design Topic')], max_length=20)),
                ('ref_id', models.PositiveIntegerField()),
                ('next_review_at', models.DateTimeField()),
                ('interval_days', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='StudySession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('focus_area', models.CharField(choices=[('DSA', 'DSA'), ('DESIGN', 'Design'), ('MIXED', 'Mixed')], default='MIXED', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DSAAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('UNSOLVED', 'Unsolved'), ('PARTIAL', 'Partial'), ('SOLVED', 'Solved')], default='UNSOLVED', max_length=20)),
                ('time_taken_minutes', models.PositiveIntegerField(default=0)),
                ('mistakes', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.dsaproblem')),
            ],
        ),
        migrations.AddField(
            model_name='dsaproblem',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='dsa_problems', to='api.tag'),
        ),
        migrations.CreateModel(
            name='DesignTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('HLD', 'HLD'), ('LLD', 'LLD'), ('DB', 'DB'), ('CACHE', 'Cache'), ('QUEUE', 'Queue'), ('SCALING', 'Scaling'), ('CONSISTENCY', 'Consistency')], default='HLD', max_length=20)),
                ('notes_markdown', models.TextField(blank=True)),
                ('tradeoffs', models.TextField(blank=True)),
                ('references_json', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='design_topics', to='api.tag')),
            ],
        ),
    ]
