# Generated by ChatGPT on 2026-02-03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_tag_unique_tag_per_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dsaproblem",
            name="workspace_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="dsaproblem",
            name="approaches_json",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="dsaproblem",
            name="bucket_labels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="dsaproblem",
            name="is_important",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="dsaproblem",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="designtopic",
            name="bucket_labels",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="designtopic",
            name="is_important",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="designtopic",
            name="is_done",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="designtopic",
            name="canvas_json",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
